-- ==========================================================
-- SKEMA DATABASE SUPABASE: PROFILES & TRANSACTIONS
-- ==========================================================

-- 1. TABEL PROFILES & TRIGGER OTOMATIS
------------------------------------------------------------
create table public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  role text check (role in ('user', 'admin')) default 'user' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Aktifkan RLS untuk profiles
alter table public.profiles enable row level security;

-- Policy profiles
create policy "Public profiles are viewable by everyone" 
on public.profiles for select using (true);

create policy "Users can update own profile" 
on public.profiles for update using (auth.uid() = id);

-- Fungsi trigger otomatis saat user baru mendaftar
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, role)
  values (new.id, 'user');
  return new;
end;
$$ language plpgsql security definer;

-- Buat trigger pada auth.users
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. TABEL TRANSACTIONS & SECURITY RLS
------------------------------------------------------------
create table public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  type text check (type in ('income', 'expense')) not null,
  category text not null,
  amount numeric not null,
  description text not null,
  transaction_date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Aktifkan RLS untuk transactions
alter table public.transactions enable row level security;

-- Policy keamanan transactions (User kelola miliknya sendiri, Admin bisa akses semua)
create policy "User dan Admin mengelola data keuangan"
on public.transactions
for all
using (
  auth.uid() = user_id 
  or 
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'admin'
  )
);